### PR TITLE
CFP-26438: Network Policy Correlation

### PR DESCRIPTION
**Pull request by hacktivist123**
This PR stores [CFP-26438](https://docs.google.com/document/d/1puY1kAwZ7QK4Kfpn3kDjo3tCh5OzgOIkxL3rQzosVFI/edit?usp=sharing) in Git to preserve it for future reference. 

Author of the CFP: @sypakine

### CODE REVIEW

**Comment by xmulligan** [comment]
@sypakine are you still working on this CFP?

**Comment by sypakine** [comment]
> @sypakine are you still working on this CFP?

This was implemented by @chancez in https://github.com/cilium/cilium/pull/27854.

I actually just [merged a PR](https://github.com/cilium/cilium/pull/33913) to bring the implementation closer to that defined in the CFP. At least point however, I feel that the CFP is redundant/obsolete.

**Comment by xmulligan** [comment]
We recently introduced statuses for CFPs https://github.com/cilium/design-cfps#status. It looks like it would fall under Released now. Would you mind making any minor updates that you think are missing so that we can merge this into the repo to document it?

**Comment by sypakine** [comment]
Sure thing, i'll work on that early next week if that's OK.

**Comment by xmulligan** [comment]
Perfect, thank you!

**Comment by sypakine** [comment]
created a new PR for this (hope that's OK): https://github.com/cilium/design-cfps/pull/51

**Pull request closed without merging**
