### PR TITLE
CFP-25813: Enhanced HTTPS Observability: Capturing Server Name Indication (SNI) in hubble without Traffic Decryption

### PR DESCRIPTION
**Pull request by hacktivist123**
This PR stores [CFP-25813](https://docs.google.com/document/d/1qlq8zUaloQutU71LG706FNLKZhbbLaZbMz-gOnC-nqo/edit?usp=sharing) in Git for future reference

Author of the CFP: @m-yosefpor

### CODE REVIEW

**Comment by joestringer** [comment]
Is there an issue filed on https://github.com/cilium/cilium for this one? If yes, then we can adopt the issue number for that instead of the `2023-10-12` CFP number.

**Comment by hacktivist123** [comment]
yes there is, that will be [25813](https://github.com/cilium/cilium/issues/28513)

**Comment by joestringer** [comment]
Could you also go through and take the title from each CFP and paste that as the title for the PR? It's a bit hard to understand the context of each PR if the title of the PR is just a number.

**Comment by xmulligan** [comment]
@m-yosefpor are you still interested in working on this CFP or should we close this PR for now?

**Comment by joestringer** [comment]
Closing due to inactivity. If you'd like to further explore this idea, please update the latest status on the upstream issue or reopen a fresh PR on this repo.

**Pull request closed without merging**
